const output = document.getElementById('output');
const vehicleInput = document.getElementById('vehicleInput');
const lineupInput = document.getElementById('lineupInput');
const vehicleList = document.getElementById('vehicleList');
const mode = document.getElementById('mode');
let vehicles = [];

function normalize(text) { return String(text || '').trim().toLowerCase().replace(/\s+/g, ' '); }
function findVehicle(name) { const target = normalize(name); return vehicles.find(v => normalize(v.name) === target); }
function escapeHtml(value) { return String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c])); }
function modeBr(v) { const m=mode.value.toLowerCase(); const key=m.includes('arcade')?'br_ab':m.includes('sim')?'br_sb':'br'; return typeof v[key]==='number'?v[key]:null; }
function rankValue(v) { if(typeof v==='number') return v; const r={i:1,ii:2,iii:3,iv:4,v:5,vi:6,vii:7,viii:8,ix:9,x:10}; return r[normalize(v)] ?? null; }
function special(v) { return /escuadrón|evento|battle pass|premium/i.test(v.availability||''); }

function imageMarkup(v) { if (!v.image_url) return '<div class="vehicle-image placeholder">SIN IMAGEN VERIFICADA</div>'; return `<div class="vehicle-image"><img src="${escapeHtml(v.image_url)}" alt="${escapeHtml(v.name)}" loading="lazy" onerror="this.parentElement.classList.add('broken');this.remove()"></div>`; }
function card(v, base=false) { const br=modeBr(v); return `<article class="vehicle-card ${base?'base':''}">${imageMarkup(v)}<div class="vehicle-info"><h3>${escapeHtml(v.name)}${base?' ← BASE':''}</h3><p>BR: ${br ?? 'pendiente'}</p><p>Rol: ${escapeHtml(v.role||'N/D')}</p><p>Estado: ${escapeHtml(v.availability||'no indicado')}</p></div></article>`; }

function analyze() { const v=findVehicle(vehicleInput.value); if(!v){output.innerHTML='<div class="warning"><strong>VEHÍCULO NO ENCONTRADO</strong><br>No existe una coincidencia exacta en la base de datos local.</div>';return;} output.innerHTML=`<div class="result-head"><div><p class="eyebrow">VEHICLE ANALYSIS</p><h2>${escapeHtml(v.name)}</h2></div><span class="badge">${escapeHtml(v.nation||'NACIÓN N/D')}</span></div><div class="cards">${card(v,true)}</div>`; }
function role(v){const text=normalize(`${v.role||''} ${v.type||''}`);if(/antiaéreo|antiaereo|spaa/.test(text))return'antiaereo';if(/atgm|antitanque|cazacarros/.test(text))return'antitanque';if(/explorador|recon|vehículo ligero|vehiculo ligero/.test(text))return'recon';if(/helicóptero|helicoptero/.test(text))return'helicoptero';if(/avión|avion|fighter|bomber|strike/.test(text))return'aire';return'principal';}
function generateLineup(){const base=findVehicle(vehicleInput.value);if(!base){output.innerHTML='<div class="warning"><strong>CONSULTA INVÁLIDA</strong><br>Introduce un vehículo que exista en la base de datos.</div>';return;}const b=modeBr(base);if(b===null){output.innerHTML=`<div class="warning"><strong>DATOS INSUFICIENTES</strong><br>${escapeHtml(base.name)} no tiene BR verificado para ${escapeHtml(mode.value)}.</div>`;return;}const candidates=vehicles.filter(v=>normalize(v.nation)===normalize(base.nation)&&v!==base&&modeBr(v)!==null&&Math.abs(modeBr(v)-b)<=0.7);const selected=[base],roles=new Set();candidates.sort((a,z)=>Math.abs(modeBr(a)-b)-Math.abs(modeBr(z)-b));for(const v of candidates){const r=role(v);if(!roles.has(r)||selected.length<2)selected.push(v),roles.add(r);if(selected.length>=5)break;}output.innerHTML=`<div class="result-head"><div><p class="eyebrow">LINEUP INTELLIGENCE</p><h2>Lineup recomendado</h2><p class="hero-text">Base: ${escapeHtml(base.name)} · ${escapeHtml(mode.value)} · BR ${b}</p></div><span class="badge">${escapeHtml(base.nation)}</span></div><div class="cards">${selected.map((v,i)=>card(v,i===0)).join('')}</div>`;}

function searchExactLineup(){const raw=lineupInput.value.trim();if(!raw){output.innerHTML='<div class="warning"><strong>LINEUP VACÍO</strong><br>Introduce los vehículos separados por comas.</div>';return;}const names=raw.split(',').map(s=>s.trim()).filter(Boolean),found=[],missing=[],seen=new Set();for(const name of names){const key=normalize(name);if(seen.has(key))continue;seen.add(key);const v=findVehicle(name);if(v)found.push(v);else missing.push(name);}if(missing.length){output.innerHTML=`<div class="warning"><strong>LINEUP NO ENCONTRADO</strong><br>Faltan en la base de datos:<br><br>${missing.map(escapeHtml).join('<br>')}</div>`;return;}const brs=found.map(modeBr).filter(x=>x!==null),nations=[...new Set(found.map(v=>normalize(v.nation)).filter(Boolean))];const brText=brs.length===found.length?`BR ${Math.min(...brs).toFixed(1)}–${Math.max(...brs).toFixed(1)}`:'BR pendiente';output.innerHTML=`<div class="result-head"><div><p class="eyebrow">EXACT LINEUP SEARCH</p><h2>Lineup verificado</h2><p class="hero-text">${found.length} vehículos · ${escapeHtml(nations.length===1?found[0].nation:'Naciones mixtas')} · ${escapeHtml(brText)}</p></div><span class="badge">COINCIDENCIA EXACTA</span></div><div class="cards">${found.map((v,i)=>card(v,i===0)).join('')}</div>`;}

function readiness(){const v=findVehicle(vehicleInput.value);if(!v){output.innerHTML='<div class="warning"><strong>VEHÍCULO NO ENCONTRADO</strong><br>Selecciona un vehículo existente.</div>';return;}const playerRank=Number(document.getElementById('playerRank').value)||null;const playerBr=Number(document.getElementById('playerBr').value)||null;const targetBr=modeBr(v),targetRank=rankValue(v.rank);const brGap=targetBr!==null&&playerBr!==null?targetBr-playerBr:null;const rankGap=targetRank!==null&&playerRank!==null?targetRank-playerRank:null;const reasons=[];if(brGap!==null&&brGap>=2)reasons.push(`BR +${brGap.toFixed(1)} sobre tu progresión habitual`);if(rankGap!==null&&rankGap>=2)reasons.push(`Rango +${rankGap} sobre tu progresión habitual`);if(special(v))reasons.push(`vehículo de ${v.availability}`);let level='NORMAL';if(brGap===null)level='SIN DATOS';else if(brGap>=4||(rankGap!==null&&rankGap>=4))level='CRÍTICO';else if(brGap>=2||(rankGap!==null&&rankGap>=2))level='ALTO';else if(brGap>=1)level='MODERADO';const tutorials=[];if(/air/i.test(mode.value)||v.category==='aircraft'){tutorials.push(['Tipos de misiles aire-aire','beginner'],['Misiles aire-tierra y tipos de guiado','intermediate'],['Cohetes y ataque en picado','beginner'],['Bombas y cálculo de lanzamiento','beginner']);if((targetBr||0)>=14)tutorials.push(['RWR: símbolos, amenazas y prioridad','beginner'],['Radar: búsqueda, alcance y contactos','beginner'],['ACM, STT y TWS','intermediate'],['RWR + radar + datalink','intermediate'],['BVR y lectura del espacio aéreo','advanced']);else tutorials.push(['Lock, alcance y ventana de lanzamiento','beginner'],['Energía, velocidad y capacidad de giro del misil','intermediate'],['Contramedidas y cómo leer la amenaza','intermediate']);}else{tutorials.push(['Identificación de puntos débiles','beginner'],['APFSDS y selección de munición','beginner']);if((targetBr||0)>=12.7)tutorials.push(['LWS: lectura y reacción','beginner'],['Telémetro láser y tiro de primer disparo','beginner'],['Termales y reconocimiento de objetivos','beginner'],['Óptica del comandante','intermediate'],['Hunter-killer y adquisición de objetivos','intermediate'],['Radar SPAA y seguimiento de blancos','advanced']);else tutorials.push(['Cómo combatir MBT superiores en uptier','intermediate'],['Posicionamiento y supervivencia contra vehículos modernos','advanced']);}
const warning=['CRÍTICO','ALTO'].includes(level);output.innerHTML=`<div class="result-head"><div><p class="eyebrow">PLAYER READINESS</p><h2>Salto tecnológico: ${level}</h2><p class="hero-text">${escapeHtml(v.name)} · ${escapeHtml(mode.value)} · BR ${targetBr??'pendiente'}</p></div><span class="badge">${warning?'PREPARACIÓN RECOMENDADA':'ANÁLISIS'}</span></div><div class="data-note">${reasons.length?reasons.map(escapeHtml).join(' · '):'No se detectó un salto grande con los datos introducidos.'}</div><h3>TUTORIALES PRIORITARIOS</h3><div class="tutorial-list">${tutorials.slice(0,8).map((t,i)=>`<div class="tutorial-item"><strong>${i+1}. ${escapeHtml(t[0])}</strong><span>${escapeHtml(t[1].toUpperCase())}</span></div>`).join('')}</div>`;}

async function loadDatabase(){try{const response=await fetch('vehicles.json',{cache:'no-store'});if(!response.ok)throw new Error('HTTP '+response.status);const data=await response.json();vehicles=Array.isArray(data.vehicles)?data.vehicles:[];document.getElementById('vehicleCount').textContent=vehicles.length;document.getElementById('verifiedCount').textContent=vehicles.filter(v=>typeof v.br==='number').length;vehicleList.innerHTML=vehicles.map(v=>`<option value="${escapeHtml(v.name)}"></option>`).join('');}catch(error){document.getElementById('vehicleCount').textContent='ERR';document.getElementById('verifiedCount').textContent='ERR';output.innerHTML='<div class="warning"><strong>DATABASE OFFLINE</strong><br>No se pudo cargar vehicles.json.</div>';}}
document.getElementById('analyzeBtn').addEventListener('click',analyze);document.getElementById('lineupBtn').addEventListener('click',generateLineup);document.getElementById('exactLineupBtn').addEventListener('click',searchExactLineup);document.getElementById('readinessBtn').addEventListener('click',readiness);vehicleInput.addEventListener('keydown',e=>{if(e.key==='Enter')analyze();});lineupInput.addEventListener('keydown',e=>{if(e.key==='Enter')searchExactLineup();});loadDatabase();
